# Generated by Django 5.1.3 on 2024-11-14 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('crew_id', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('site_engineer', 'Site Engineer'), ('supervisor', 'Supervisor')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CrewJobAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_count', models.IntegerField(default=1)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMSApp.crew')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_order_id', models.CharField(max_length=100, unique=True)),
                ('job_type', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
                ('crews', models.ManyToManyField(blank=True, through='CMSApp.CrewJobAssignment', to='CMSApp.crew')),
            ],
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('units_completed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('work_notes', models.TextField(blank=True, null=True)),
                ('crew', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_logs', to='CMSApp.crew')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='CMSApp.job')),
            ],
        ),
        migrations.AddField(
            model_name='crewjobassignment',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMSApp.job'),
        ),
    ]
